// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFp8ZpRLPSa4C31FdG6YknYETTYzCmbtk',
    appId: '1:219349092108:web:66198668e8c07f7f1d6b29',
    messagingSenderId: '219349092108',
    projectId: 'havenmall',
    authDomain: 'havenmall.firebaseapp.com',
    storageBucket: 'havenmall.appspot.com',
    measurementId: 'G-9WLLH0X146',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXztkJSmFuSRD15x4iPlFiDcAvnajCdh0',
    appId: '1:219349092108:android:6ef777fd10a3b62e1d6b29',
    messagingSenderId: '219349092108',
    projectId: 'havenmall',
    storageBucket: 'havenmall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIDPtFnwy12sIaYC_YO7jy-4IaPuvodhk',
    appId: '1:219349092108:ios:dd88ad3b47bac77a1d6b29',
    messagingSenderId: '219349092108',
    projectId: 'havenmall',
    storageBucket: 'havenmall.appspot.com',
    iosClientId: '219349092108-0qp41p2b5aiu9uebau0nb4g5scarejip.apps.googleusercontent.com',
    iosBundleId: 'com.example.havenmall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIDPtFnwy12sIaYC_YO7jy-4IaPuvodhk',
    appId: '1:219349092108:ios:612666222dcea7a11d6b29',
    messagingSenderId: '219349092108',
    projectId: 'havenmall',
    storageBucket: 'havenmall.appspot.com',
    iosClientId: '219349092108-7v1bgtbff2t8mcvgo714c08vbsmtkdss.apps.googleusercontent.com',
    iosBundleId: 'com.example.havenmall.RunnerTests',
  );
}
